apiVersion: v1
kind: Service
metadata:
  name: cassandra-cluster-ip-service
  namespace: intimations
spec:
  ports:
    - name: "cql"
      protocol: "TCP"
      port: 9042
      targetPort: 9042
      nodePort: 0
