apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: employee-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
        - name: employee
          image: "codingkapoor/employee-impl:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx256m -Dconfig.resource=prod-application.conf"
            - name: APPLICATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: intimations-application-secret
                  key: secret
            - name: MYSQL_URL
              value: "jdbc:mysql://mysql/intimations_employee_schema"
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: intimations-mysql-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: intimations-mysql-secret
                  key: password
            - name: CASSANDRA_CONTACT_POINT
              value: cassandra
            - name: KAFKA_SERVICE_NAME
              value: "_broker._tcp.kafka.default.svc.cluster.local"
            - name: REQUIRED_CONTACT_POINT_NR
              value: "1"
          ports:
            - name: management
              containerPort: 8558
          readinessProbe:
            httpGet:
              path: "/ready"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              path: "/alive"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
