apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: employee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
        - name: employee
          image: "codingkapoor/employee-impl:latest"
          imagePullPolicy: Never
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx256m -Dconfig.resource=prod-application.conf"
            - name: APPLICATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: employee-application-secret
                  key: secret
            - name: MYSQL_URL
              value: "jdbc:mysql://10.0.2.2/intimations_employee_schema"
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-employee-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-employee-secret
                  key: password
            - name: KAFKA_SERVICE_NAME
              value: "_clients._tcp.strimzi-kafka-brokers"
            - name: REQUIRED_CONTACT_POINT_NR
              value: "1"
          ports:
            - name: management
              containerPort: 8558
          readinessProbe:
            httpGet:
              path: "/ready"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              path: "/alive"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: employee
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9000
  selector:
    app: employee
  type: LoadBalancer
