apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: passwordless-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passwordless
  template:
    metadata:
      labels:
        app: passwordless
    spec:
      containers:
        - name: passwordless
          image: "codingkapoor/passwordless-impl:latest"
          imagePullPolicy: Never
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx256m -Dconfig.resource=prod-application.conf"
            - name: APPLICATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: intimations-application-secret
                  key: secret
            - name: MYSQL_URL
              value: "jdbc:mysql://mysql/intimations_passwordless_schema"
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: intimations-mysql-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: intimations-mysql-secret
                  key: password
            - name: MAILER_SMTP_INTERFACE
              value: "mymail.myoutlookonline.com"
            - name: MAILER_SMTP_PORT
              value: "587"
            - name: MAILER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: intimations-mailer-secret
                  key: email
            - name: MAILER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: intimations-mailer-secret
                  key: password
            - name: ACCESS_TOKEN_EXPIRY_IN_MINUTES
              value: "46000"
            - name: REFRESH_TOKEN_EXPIRY_IN_MONTHS
              value: "12"
            - name: OTP_EXPIRY_IN_MINUTES
              value: "1"
            - name: KAFKA_SERVICE_NAME
              value: "_broker._tcp.kafka.default.svc.cluster.local"
            - name: REQUIRED_CONTACT_POINT_NR
              value: "1"
          ports:
            - name: management
              containerPort: 8558
          readinessProbe:
            httpGet:
              path: "/ready"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              path: "/alive"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
